apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: client-to-server
  namespace: default
spec:
  destination:
    name: static-server
  sources:
    - name: static-client
      action: deny
